### ISSUE TITLE
Documentation on using the example echo-service

### ISSUE THREAD

**Issue by jonniespratley** [ActiveState/cf-services-connector-nodejs#3]
Currently this repository has an example `echo-service` located in the `examples` folder. There is no information on what to do with and how to use the `echo-service`.

It would be great if you could:

1. Provide code examples for creating a simple node.js application that uses the service.
2. Workflow after creating a custom service, such as adding it to cloud foundry, adding it to an application, using it in the application. etc.

**Comment by btat** [comment]
Hi jonniespratley, the included echo-service example only demonstrates an implementation of the various functions (bind, unbind, provision, unprovision) required of a service broker. The example can be provisioned and bound to an app but has no other functionality beyond that. Hence, the lack of specific instructions on using it.

By performing the steps noted in the [Register the broker with the CC](https://github.com/ActiveState/cf-services-connector-nodejs#register-the-broker-with-the-cc) section you are effectively adding the service to Cloud Foundry.  Additional information regarding binding/adding the service to an application and using it have been added.

Feel free to reopen this issue if you have further concerns.

**Comment by jonniespratley** [comment]
Thank you.
