### ISSUE TITLE
 ReferenceError: Enryptor is not defined on bind request

### ISSUE THREAD

**Issue by mvanholsteijn** [ActiveState/cf-services-connector-nodejs#4]
When I perform a bind request, the framework fails to respond with the following error:

 ReferenceError: Enryptor is not defined
./node_modules/aws-sdk/lib/request.js:32

**Comment by mvanholsteijn** [comment]
Great fix! Can you publish version 0.2.5 to npm please so I can use it?

**Comment by shsu** [comment]
Done!
